name: unit_testing

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    container: argovis/argovis_helpers:test-base-240418

    services:
      database:
        image: argovis/testdb:0.41
      redis:
        image: redis:7.0.2
      api:
        image: argovis/api:2.24.3
        env:
          ARGONODE: core

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run_tests
        run: pytest tests/*.py